### PR TITLE
Improve code and make just string options work 

### PR DESCRIPTION
**Pull request by WilsontheWolf**

### CODE REVIEW

**Comment by thetayloredman** [comment]
Oh my I could **not** have noticed those typos, my editor's theme makes block comments red, and the background is **black** (*like actual `#00000`*) and it's so hard to read, so thanks!

**Review by thetayloredman — APPROVED** [review]

**Comment by thetayloredman** [comment]
Merged 484e97d into `master`.

**Comment by WilsontheWolf** [comment]
> Oh my I could not have noticed those typos
My editor yells at me with typos.

**Comment by thetayloredman** [comment]
What editor?

**Comment by WilsontheWolf** [comment]
VSCode with this extension https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker

**Comment by thetayloredman** [comment]
LMAO I found it before that comment, thanks tho!

**Pull request merged**
